server:
  port: ${PORT:8000}
spring:
  h2:
    console:
      enabled: true
      path: /hotpeppers-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:hotpeppers-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: hotpeppersadmin
    password: hotpepperspwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
springdoc:
  swagger-ui:
    path: /hotpeppers-endpoints
    operationsSorter: true
jwt:
  secret: secret